getvyt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('invite.urls')) 
]

invite/urls.py
from django.urls import path

from . import views

app_name = 'invite'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('friend-request/accept', views.accept_friendship, name='accept_friend_request'),
    path('event/add/attendee', views.add_attendee, name='add_attendee'), 
    path('add/friend', views.add_friend, name='add_friend'),
    path('waitlist/join', views.add_to_waiting_list, name='add_to_waiting_list'),
    path('search/recent/add/<str:username>', views.add_to_recent_searches, name='add_to_recent'),
    path('calendar', views.view_calendar, name='view_calendar'),
    path('calendar/events', views.calendar_events, name='calendar_events'),
    path('checkout', views.checkout, name='checkout'),
    path('confirm', views.confirm_email, name='confirm_email'),
    path('new-event/publish', views.create_event, name='save_event'),
    path('friend/remove', views.delete_friendship, name='delete_friendship'),
    path('profile/add/about', views.edit_about, name='edit_about'),
    path('profile/add/image', views.edit_profile_img, name='edit_profile_image'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('profile/edit/email', views.edit_email, name='edit_email'),
    path('profile/edit/fullname', views.edit_fullname, name='edit_fullname'),
    path('profile/edit/username', views.edit_username, name='edit_username'),
    path('event/share/<int:event_id>', views.event_shared_handler, name='share_event'),
    path('<str:username>/friends/new', views.find_friends, name='find_friends'),
    path('follow/<str:username>', views.follow, name='follow'),
    path('retrieve-api-key/<str:token_name>', views.get_API_key, name='retrieve_API_key'),
    path('get/<str:get_query>', views.get_data, name='get_data'),
    path('event/ticket/get/<int:event_id>', views.get_event_access, name='get_ticket'),
    path('events/get', views.get_events, name='get_events'),
    path('events/get/filter/nearby', views.get_events_nearby, name='get_events'),
    path('events/get/filter/<str:filter_by>', views.get_events_filter, name='get_events'),
    path('event/stats/<int:event_id>', views.get_event_stats, name='event_stats'),
    path('get/followers/<str:username>', views.get_followers, name='get_followers'),
    path('get/followings/<str:username>', views.get_followings, name='get_followings'),
    path('friends/<str:username>', views.get_friends, name='get_friends'),
    path('pending-friends/<str:username>', views.get_pending_friends, name='get_pending_friends'),
    path('popular-users', views.get_popular_accounts, name='popular_accounts'),
    path('profile/count/<str:username>', views.get_profile_count, name='profile_count'),
    path('saved-events', views.get_saved_events, name='get_saved_events'),
    path('ticket/new/add', views.get_ticket, name='get_ticket'),
    path('ticket/<int:event_id>', views.get_ticket_info, name='get_ticket_info'),
    path('bio/<str:username>', views.get_user_bio, name='user_bio'),
    path('get-info-about-user/<str:username>', views.get_user_data, name='get_user_data'),
    path('profile_image/<str:username>', views.get_user_profile_image, name='user_profile_img'),
    path('get-username', views.get_username, name='get_username'),
    path('home', views.index, name='index'),
    path('is-event-refundable/<int:event_id>', views.is_event_refundable, name='is_event_refundable'),
    path('is-user-authenticated/<str:username>', views.is_user_authenticated, name='is_user_authenticated'),
    path('check/is-user-following/<str:other_user>', views.is_user_following, name='check_user_follow_status'),
    path('logged-in', views.is_user_logged_in, name='logged_in_status'),
    path('login-with-dummy-account', views.login_with_dummy_account, name="dummy_login"),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('main', views.main, name='main'),
    path('metrics', views.metrics, name='metrics'),
    path('metrics/stats', views.metrics_stats, name='metrics_stats'),
    path('more-info/<int:event_id>/edit', views.more_info, name='more_info'),
    path('more-info/<int:event_id>/edit/get/draft', views.get_event_draft, name='get_more_info'),
    path('more-info/<int:event_id>/edit/draft/save', views.more_info, name='save_more_info'),
    path('more-info/<int:event_id>/view', views.view_more_info, name='view_more_info'),
    path('more-info/<int:event_id>/event/view', views.event_more_info_render, name='save_event_id'),
    path('new_password/<str:username>/<str:access>', views.new_password, name='new_password'),
    path('notifications', views.get_notifications, name='get_notifications'),
    path('notification/push/top', views.push_top_notification, name='push_top_notification'),
    path('new-event', views.new_event, name='new_event'),
    path('search/recent', views.recent_search, name='recent_search'),
    path('event/refund', views.refund_handler, name='handler_refunds'),
    path('register', views.register_view, name='register'),
    path('event/remove/attendee', views.remove_attendee, name='remove_attendee'),
    path('page-not-found', views.render404, name='render404'),
    path('resend-code', views.resend_code, name='resend_code'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('event/save', views.save_event, name='save_event'),
    path('ticket/scan/<str:event_id>/<str:ticket_id>', views.validate_ticket, name='scan_tickets'),
    path('scan-tickets/<str:event_id>', views.scan_tickets, name='scan_tickets_view'),
    path('search', views.search, name='search_user'),
    path('unfollow/<str:username>', views.unfollow, name='unfollow'),
    path('personalization/increment-scores', views.update_scores, name='follow_scores'),
    path('saved-event/delete', views.unsave_event, name='unsave_event'),
    path('wallet', views.wallet_view, name='wallet'),
    path('wallet/balance', views.wallet_balance, name='deposit'),
    path('wallet/deposit', views.wallet_deposit, name='deposit'),
    path('<str:username>', views.profile, name='profile'),
]

invite/views.py
from datetime import date, datetime, timedelta
from io import BytesIO
from json import dumps, loads
from tempfile import NamedTemporaryFile
from uuid import uuid4

import requests

from PIL import Image
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.files import File
from django.core.files.storage import default_storage
from django.core.mail import send_mail
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.timezone import localtime, now
from fuzzywuzzy import process
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from sklearn.feature_extraction.text import TfidfVectorizer
from urllib.parse import unquote


from .models import *
from getvyt.settings import MAPBOX_ACCESS_TOKEN, OPENAI_ACCESS_TOKEN, HOST_URL
from .utils import *

ACTIONS = {
    'buy_ticket': 500,
    'attend_free_event': 400,
    'read_more_info': 280,
    'save_event': 330,
    'see_more': 75,
    'share_event': 350,
    'see_exact_location': 260,
    'follow_organiser': 220,
    'open_post_discuss': 180,
    'write_post_discuss': 200,
    'react_to_stories': 180,
    'share_post_discussion': 250,
    'add_new_friend': 100,
    'new_follow': 50,
    'search_user': 30,
}

@login_required(login_url='/login')
def accept_friendship(request):
    if request.method == 'POST':
        data = loads(request.body)
        username = data.get('username', '')
        other_user = User.objects.get(username=username)
        logged_in_user = request.user

        # Ensure the friend request exists
        friendship = FriendRequest.objects.filter(requester=logged_in_user, receivers=other_user)
        if not friendship.exists(): 
            friendship = FriendRequest.objects.filter(requester=other_user, receivers=logged_in_user)
        else:
            friendship.first().receivers.remove(other_user)

        if not friendship.exists():
            return JsonResponse({'error': 'No friend request was found'}, status=400)
        else:
            friendship.first().receivers.remove(logged_in_user)

        # Check existing connections
        connection = Friend.objects.filter(user=logged_in_user, friend=other_user).first()
        if connection:
            connection.status = Friend.ACCEPTED
            connection.save()

            con2 = Friend.objects.filter(user=other_user, friend=logged_in_user).first()
            con2.status = Friend.ACCEPTED
            con2.save()

        else:
            # Create a new friendship
            Friend.objects.create(user=logged_in_user, friend=other_user, status=Friend.ACCEPTED)
            Friend.objects.create(user=other_user, friend=logged_in_user, status=Friend.ACCEPTED)

        return JsonResponse({}, status=200)


@login_required(login_url='/login')
def add_attendee(request):
    user = request.user
    data = loads(request.body)
    event_id = int(data.get('eventId', ''))

    event = get_object_or_404(Event, id=event_id)

    if event.ticket_access:
        return JsonResponse(
            {'error': 'The event has a ticket access and must be accessed through a different route'}, 
        status=400)

    if event.attendees_allowed > 0:
        if event.attendees.count() >= event.attendees_allowed:
            return JsonResponse({'error': 'The number of attendees has reached the limit'}, status=401)

    event.attendees.add(user)

    saved_events, created = SavedEvent.objects.get_or_create(user=user)
    if created:
        saved_events.event.set([event])
    else:
        saved_events.event.add(event)

    # Notify the friends of the attendee
    friends = Friend.objects.filter(user=user, status=status.ACCEPTED)

    for friend in friends:
        notification = Notification.objects.create(
            origin=user,
            to=friend.friend,
            notification_type=notification_type.friend_attending
        )
        notification.save()

    return JsonResponse({}, status=200)


@login_required(login_url='/login')
def add_friend(request):
    if request.method == 'POST':
        data = loads(request.body)
        friend_username = data.get('username', '')
        friend = get_object_or_404(User, username=friend_username)

        # Check if a friend request already exists between the users
        existing_request = FriendRequest.objects.filter(requester=request.user, 
            receivers=friend, 
            status=FriendRequest.PENDING).first()

        if existing_request:
            # A pending request already exists
            return JsonResponse({'error': 'Friend request already sent'}, status=400)
        else:
            # Create a new friend request
            new_request, created = FriendRequest.objects.get_or_create(requester=request.user)
            new_request.receivers.add(friend)

            # TODO: Add Notification

            return JsonResponse({}, status=200)


def add_to_waiting_list(request):
    email = request.GET.get('email')
    waiting = WaitingList.objects.filter(email=email)
    if waiting.exists():
        return JsonResponse({'error': 'conflict'}, status=409)

    WaitingList.objects.create(email=email)
    return JsonResponse({}, status=200)


@login_required(login_url='/login')
def add_to_recent_searches(request, username):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return JsonResponse({}, status=401)

        recent = list(Recent.objects.filter(user=request.user))

        for user in recent:
            if user.recent.username == username.strip():
                return JsonResponse({}, status=409)

        # If recent size is 3 or more, delete the last element
        if len(recent) >= 3:
            recent_queryset = Recent.objects.filter(user=request.user).order_by('-id')
            recent_queryset.last().delete()

        user = get_object_or_404(User, username=username)

        # Add new user to recent
        Recent.objects.create(user=request.user, recent=user)

        return JsonResponse({}, status=200)


@login_required(login_url='/login')
def calendar_events(request):
    user = request.user
    attending = Event.objects.filter(attendees=user)
    saved = SavedEvent.objects.filter(user=user).values('event')
    print('saved', saved)
    saved_events = Event.objects.filter(id__in=[e['event'] for e in saved])
    combined = attending.union(saved_events)

    events = []
    for event in combined:
        obj = {
            'title': event.title,
            'start': int(convert_datetime_to_timestamp(event.datetime)),
            'end': int(convert_datetime_to_timestamp(event.end_datetime))
        }
        events.append(obj)

    return JsonResponse({'events': events}, status=200)


@login_required(login_url='/login')
def confirm_email(request):
    if request.method == 'POST':
        data = loads(request.body)
        user = User.objects.get(username=request.session['username'])

        if int(data.get('code', '')) != user.email_code:
            return JsonResponse({'error_type': 'confirm_code_not_match'}, status=400)

        time_difference = localtime() - user.code_generation_date
        if (time_difference).seconds > 916:
            user.email_code = generate_code()
            user.code_generation_date = localtime()
            user.save()
            send_mail(
                'Welcome to GetVyt',
                f'Hello, {user.first_name}. Use this code: {user.email_code} to confirm your email.',
                'portfolio@livingdreams.com',
                [user.email],
                fail_silently=False,
            )
            return JsonResponse({'error_type': 'confirm_code_expired'}, status=400)

        user.is_email_confirmed = True
        user.save()

        if not ProfileSetUp.objects.filter(user=user).exists():
            ProfileSetUp.objects.create(user=user)

        login(request, user)

        return JsonResponse({}, status=200)

    else:
        return render(request, 'invite/confirm_email.html')


def extract_keywords(event_id):
    event = Event.objects.get(id=event_id)

    text = event.description

    # Tokenize the text into words
    tokens = nltk.word_tokenize(text.lower())

    # Remove stop words
    stop_words = set(nltk.corpus.stopwords.words('english'))
    words = [token for token in tokens if token.isalnum() and token not in stop_words]

    # Extract keywords using TF-IDF
    tfidf = TfidfVectorizer()
    tfidf.fit(words)
    keywords = dict(zip(tfidf.vocabulary_.keys(), tfidf.idf_))

    # Save the keywords in the database
    event_keywords = EventKeyword(event=event, keywords=keywords)
    event_keywords.save()

    return


@login_required(login_url='/login')
def create_event(request):
    if request.method == 'POST':

        # Validate form
        title = request.POST.get('title')
        if not title:
            return JsonResponse({'error_type': 'event_title_empty'}, status=400)

        description = request.POST.get('description')
        if not description:
            return JsonResponse({'error_type': 'event_description_empty'}, status=400)

        location = request.POST.get('location')
        if not location:
            return JsonResponse({'error_type': 'event_location_empty'}, status=400)

        datetimeInfo = request.POST.get('datetime')
        if not datetimeInfo:
            return JsonResponse({'error_type': 'event_datetime_empty'}, status=400)

        endingDatetimeInfo = request.POST.get('endingDatetime')
        if not endingDatetimeInfo:
            return JsonResponse({'error_type': 'event_ending_datetime_empty'}, status=400)

        selectedType = request.POST.get('selectedType')

invite/templates/invite/access.html
<!DOCTYPE html>
<html>
<body>     
<form action="x.php">
    <div class="lol">
        <h1><a href="#"><img src="menu-2.1024x682.png" width="30" height="20"></a>  Access</h1>
        <h1>Avengers: Secret Wars</h1>
        <p><img src="location-pin.761x1024.png" width="10" height="12"> Brooklyn Cinema, Pretoria  (<a href="#">See exact location</a>)</p>
        <p><img src="clock.1024x1024.png" width="12" height="12"> 11 Nov 2024, 19:40</p>
        <img src="qrcode_www.youtube.com.png" width="350" height="350">
        <br>

        <hr>
    <div class="lol2">
        <p>
            <img src="home-outline.922x1024.png" width="40" height="40" style="padding-right: 2em">
            <img src="search-outline.1024x1024.png" width="40" height="40" style="padding-right: 2em"> 
            <img src="person-add-outline.1024x970.png" width="45" height="40" style="padding-right: 2em"> 
            <img src="bookmark-outline.803x1024.png" width="30" height="40" style="padding-right: 2em"> 
            <img src="account-circle.1024x1024.png" width="47" height="47" style="padding-right: 2em"> 
            
        </p> 
    </div>    
        
</form>
        

</body>
</html> 

invite/templates/invite/calendar.html
{% extends 'invite/main.html' %}

{% load static %}

{% block title %} Calendar {% endblock %}

{% block head %}
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.5/index.global.min.js'></script>
{% endblock %}

{% block main %}

<section class='calendar-view'>
  <div id='calendar'></div>
</section>

<script>

const formatMonthForCalendar = (mon) => {
    const newMon = mon + 1;
    return newMon < 10 ? `0${newMon}` : newMon;
  }

  const formatForCalendar = (any) => {
    return any < 10 ? `0${any}` : any;
  }

  const formatDateTimeForCalendar = (timestamp) => {
    const d = new Date(timestamp);
    const year = d.getFullYear();
    const mon = formatMonthForCalendar(d.getMonth());
    const date = formatForCalendar(d.getDate());
    const h = formatForCalendar(d.getHours());
    const m = formatForCalendar(d.getMinutes());

    return `${year}-${mon}-${date}T${h}:${m}:00`;
  }

document.addEventListener('DOMContentLoaded', async function() {
  var calendarEl = document.getElementById('calendar');

  try {
    const response = await fetch('/calendar/events');
    const { events } = await response.json();

    console.log(events);

    const eventsArray = []
    for (event of events) {
      const obj = {
        title: event.title,
        start: formatDateTimeForCalendar(event.start),
        end: formatDateTimeForCalendar(event.end),
      }

      eventsArray.push(obj);
    }

    console.log(eventsArray);

    var calendar = new FullCalendar.Calendar(calendarEl, {
    initialView: 'dayGridMonth',
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay'
    },
    events: eventsArray
  });

  calendar.render();

  } catch(error) {
    alert("Sorry, an error occurred and we couldn't fetch your events. Please check your internet connection and try again later.");
    console.error(error);
  }
});
</script>

{% endblock %}

invite/templates/invite/confirm_email.html
{% extends 'invite/layout.html' %}

{% load static %}

{% block title %} Confirm Email {% endblock %}

{% block body %}

<section class='d-flex align-items-center flex-column justify-content-center form-section'>

  <div class='forms-wrapper w-100'>
    <div class='hero-section d-none d-lg-flex flex-column justify-content-center'>
      <div class='form-header font-headline text-center'>Your one-stop-shop for all the hottest events.</div>
      <div class='img-wrapper-login'>
        <img class='login-img' src='{% static "/invite/images/app/logo.svg" %}' alt='logo'>
      </div>
    </div>

    <div class='d-flex align-content-center flex-column form'>
      <img class='logo rounded-circle mb-3'
        src='{% static "invite/images/app/logo.svg" %}'
        alt='This is a logo'>

      <form>
        {% csrf_token %}

        <p class='text-center'>The code has been sent to your email. The code will expire in 15 minutes.
        </p>

        <div class='form-floating mb-3'>
          <input type='number' name='code' class='code form-control input-frame' placeholder='Enter code here' required>
          <label for='code' class='floating-input-placeholder'>Enter code here</label>
          <div class='error-message feedback-empty code-empty d-none'>
            Enter the code we sent you.
          </div>
          <div class='error-message code-long d-none'>
            The code must have only 6 digits.
          </div>
          <div class='error-message code-nan d-none'>
            The code must be a number.
          </div>
          <div class='error-message code-invalid d-none'>
            Your code is incorrect! Check your emails.
          </div>
          <div class='error-message code-expired d-none'>
            The code has expired! A new code has been sent to your email.
          </div>
        </div>

        <div class='mb-3'>
          <input type='submit' class='btn btn-primary w-100' value='Confirm Email'>
          <button class='btn btn-primary w-100 d-none' disabled>
            <span class='spinner'></span>
          </button>
        </div>
      </form>

      <div class='text-center text-primary resend-code'>
        Resend Code
      </div>
    </div>

  </div>

</section>

<script src='{% static "invite/js/utils/forms.js" %}'></script>
<script src='{% static "invite/js/confirm_email.js" %}'></script>

{% endblock %}

invite/templates/invite/edit_profile.html
{% extends 'invite/layout.html' %}

{% block title %} Edit Profile {% endblock %}

{% block body %}

<!-- Your code goes here -->
<section class='edit-profile'>
  <!-- Profile  -->

  <div class='text-center'>
    <div class="rounded-circle">
      <img class='rounded-circle'
        src='https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=800'
        alt='profile-picture' height='100'>
      <i class='bi bi-pencil-fill'></i>
    </div>
  </div>

  <!-- Name  -->
  <div class='border-bottom border-dark d-flex align-items-center justify-content-between stack'>
    <div class='d-flex align-items-center'>
      <div>
        <i class='bi bi-person'></i>
      </div>
      <div class='d-flex flex-column'>
        <span class='font-body-tiny'>Name</span><span class='imp font-body'>John Doe</span>
      </div>
    </div>
    <div>
      <i class='bi bi-pencil-fill'></i>
    </div>
  </div>

  <!-- Username  -->
  <div class='border-bottom border-dark d-flex align-items-center justify-content-between stack'>
    <div class='d-flex align-items-center'>
      <div>
        <i class='bi bi-at'></i>
      </div>
      <div class='d-flex flex-column'>
        <span class='font-body-tiny'>Username</span>
        <span class='imp font-body'>realjohndoe</span>
      </div>
    </div>
    <div>
      <i class='bi bi-pencil-fill'></i>
    </div>
  </div>

  <!-- About  -->
  <div class='border-bottom border-dark d-flex align-items-center justify-content-between stack'>
    <div class='d-flex align-items-center'>
      <div>
        <i class='bi bi-info-circle'></i>
      </div>
      <div class='d-flex flex-column'>
        <span class='font-body-tiny'>About</span><span class='imp font-body'>King of the Dark Web</span>
      </div>
    </div>
    <div>
      <i class='bi bi-pencil-fill'></i>
    </div>
  </div>

  <!-- Email -->
  <div class='border-bottom border-dark d-flex align-items-center justify-content-between stack'>
    <div class='d-flex align-items-center'>
      <div>
        <i class='bi bi-envelope'></i>
      </div>
      <div class='d-flex flex-column '>
        <span class='font-body-tiny'>Email</span><span class='imp font-body'>johndoe123@gmail.com</span>
      </div>
    </div>
    <div>
      <i class='bi bi-pencil-fill'></i>
    </div>
  </div>

</section>

{% endblock %}

invite/templates/invite/more-event-info.html
{% extends 'invite/main.html' %}

{% load static %}

{% block title %} More Info {% endblock %}

{% block main %}

  <section class='more-event-info'>
    <div class='header mb-3 d-flex align-items-center'>
      <img src='{% static "invite/images/app/logo.svg" %}' alt='logo' class='logo'/>
      <div class='font-headline ms-2'>Add More Info</div>
    </div>

    <div class='main-content'>

      <div class='text-container'></div>

      <div class='prompt-type'></div>

      <div class='add d-flex align-items-center'>
        <i class='bi bi-plus add-icon'></i>
      </div>
    </div>

    <div class='d-flex justify-content-end mt-3'>
      <button class='btn btn-primary preview-event-info me-2'>Preview</button>
      <button class='btn btn-primary-outline save-draft me-2' disabled>Save Draft</button>
      <button class='btn btn-secondary save-event-info' disabled>Save</button>
    </div>
  </section>

  <script type='text/javascript' src='{% static "invite/js/moreEventInfo.js" %}'></script>

{% endblock %}

invite/templates/invite/more-info-view.html
{% extends 'invite/main.html' %}

{% load static %}

{% block title %} More Info {% endblock %}

{% block main %} 

<section class='more-event-info'>
  <div class='header mb-3 d-flex align-items-center'>
    <img src='{% static "invite/images/app/logo.svg" %}' alt='logo' class='logo'/>
  </div>

  <div class='main-content'>
    <div class='text-container'></div>
  </div>
</section>

<script type='text/javascript' src='{% static "invite/js/index.js" %}'></script>
<script type='text/javascript' src='{% static "invite/js/moreInfoView.js" %}'></script>

{% endblock %}

invite/templates/invite/reset_password.html
{% extends 'invite/layout.html' %}

{% load static %}

{% block title %} Reset Password {% endblock %}

{% block body %}

<section class='d-flex align-items-center flex-column justify-content-center form-section'>

  <div class='forms-wrapper w-100'>
    <div class='hero-section d-none d-lg-flex flex-column justify-content-center'>
      <div class='form-header font-headline text-center'>Your one-stop-shop for all the hottest events.</div>
      <div class='img-wrapper-login'>
        <img class='login-img' src='{% static "/invite/images/app/logo.svg" %}' alt='logo'>
      </div>
    </div>

    <div class='d-flex flex-column align-items-center justify-content-center form'>

      <img class='logo mb-3 rounded-circle'
        src='{% static "invite/images/app/logo.svg" %}'
        alt='Profile Pic'>

      <form class='w-100'>
        {% csrf_token %}
        <div class='form-floating mb-3'>
          <input type='email' class='email form-control input-frame' placeholder='Email' required>
          <label for='email' class='floating-input-placeholder'>Email</label>
          <div class='error-message feedback-empty email-404 d-none'>
            Email not found on our databases! Try registering.
          </div>
          <div class='error-message link-sent d-none'>
            A link has been sent to your email, use it to reset your password.
          </div>
        </div>

        <div class='mb-3 error-message'></div>

        <div class='mb-3'>
          <input class='btn btn-primary w-100' type='submit' value='Reset Password'>
          <button class='btn btn-primary w-100 d-none' disabled>
            <span class='spinner'></span>
          </button>
        </div>

        <hr class='w-100'>
      </form>

      <a class='btn btn-secondary w-50' type='button' href='{% url "invite:login" %}'>Login</a>

    </div>
  </div>

</section>

<script src='{% static "invite/js/utils/forms.js" %}'></script>
<script src='{% static "invite/js/reset_password.js" %}'></script>

{% endblock %}

invite/templates/invite/scan-tickets.html
{% extends 'invite/main.html' %}

{% load static %}

{% block title %} Scan Tickets {% endblock %}

{% block head %}
<script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>

{% endblock %}

{% block main %}

<section class='wallet tickets-scanner p-3'>
  <div class='header mb-3 d-flex align-items-center'>
    <i class='bi bi-qr-code-scan'></i>
    <div class='font-headline ms-2'>Scan Tickets</div>
  </div>

  <div class='main-content d-flex justify-content-center align-items-center'>
    <div class='event-id d-none'>{{ event_id }}</div>
    <div class='wrapper d-flex flex-column justify-content-center align-items-center'>
      <video id='scanner'></video>
    </div>
  </div>
</section>

<script type='text/javascript' src='{% static "invite/js/scanTickets.js" %}'></script>

{% endblock %}

invite/templates/invite/settings.html
{% extends 'invite/layout.html' %}

{% block title %} Settings {% endblock %}

{% block body %}

<!-- Your code goes here -->
<section>
    <!-- Setting -->
    <div><h1><strong> <i class='fa-solid fa-gear'></i> Setting </strong></h1></div> <hr>
    <!-- Edit-profile -->
    <div><strong> <i class='fa-solid fa-user-pen'></i> Edit profile</strong></div> <hr>
    <!-- notification  -->
    <div><strong> <i class='fa-regular fa-bell'></i> Notification</strong></div> <hr>
    <!-- privacy policy -->
    <div><strong> <i class='fa-regular fa-eye'></i> Privacy Policy</strong></div> <hr>
    <!-- report an issue -->
    <div><strong> <i class='fa-solid fa-circle-info'></i> Report an Issue</strong></div> <hr>
    <!-- reset password -->
    <div><strong> <i class='fa-solid fa-lock'></i> Reset Password</strong></div> <hr>
    <script src='https://kit.fontawesome.com/0d461e2d79.js' crossorigin='anonymous'></script>
</section>    

{% endblock %}